### ISSUE TITLE
Unsupported operation: Cannot remove from an unmodifiable list

### ISSUE THREAD

**Issue by RudiUrbanek** [theideasaler/calendar_date_picker2#75]
This error occures using your package

======== Exception caught by widgets library =======================================================
The following UnsupportedError was thrown building:
Unsupported operation: Cannot remove from an unmodifiable list

When the exception was thrown, this was the stack: 
#0      UnmodifiableListMixin.removeWhere (dart:_internal/list.dart:139:5)
#1      _MonthPickerState._buildItems (package:calendar_date_picker2/src/widgets/calendar_date_picker2.dart:764:45)
#2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:487:22)
#3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1422:28)
#4      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1352:67)
#5      Iterable.forEach (dart:core/iterable.dart:325:35)
#6      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1399:24)
#7      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1328:7)

**Comment by theideasaler** [comment]
@RudiUrbanek Could you please provide a minimum reproducible code and the reproduce steps?

**Comment by Mayb3Nots** [comment]
> @RudiUrbanek Could you please provide a minimum reproducible code and the reproduce steps?

Just use the minimum working sample and it doesn't work.

```dart
CalendarDatePicker2(
  config: CalendarDatePicker2Config(),
  initialValue: [],
);
```

**Comment by theideasaler** [comment]
Hi @Mayb3Nots

> > @RudiUrbanek Could you please provide a minimum reproducible code and the reproduce steps?
> 
> Just use the minimum working sample and it doesn't work.
> 
> ```dart
> CalendarDatePicker2(
>   config: CalendarDatePicker2Config(),
>   initialValue: [],
> );
> ```
Just checked but still could not reproduce.
May I know which flutter SDK version you are using, and which platform you are running it on? And could you please see if the [examples](https://github.com/theideasaler/calendar_date_picker2/tree/main/example) works for you or not?
