### ISSUE TITLE
[Bug] Error occurs when moving the focus with the keyboard

### ISSUE THREAD

**Issue by zuvola** [theideasaler/calendar_date_picker2#9]
Thank you for your wonderful library!

**Describe the bug**
Error occurs when moving the focus with the keyboard.
It is reproduced by pressing the left/right key after moving the focus to the calendar section with the Tab key.

<details>
<summary>Error log</summary>

```

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown while processing the key message handler:
'package:calendar_date_picker2/src/widgets/calendar_date_picker2.dart': Failed assertion: line 680 pos 12: '_focusedDay != null': is not true.

When the exception was thrown, this was the stack
#2      _MonthPickerState._handleDirectionFocus
#3      CallbackAction.invoke
#4      ActionDispatcher.invokeAction
#5      ShortcutManager.handleKeypress
#6      _ShortcutsState._handleOnKey
#7      FocusManager._handleKeyMessage
#8      KeyEventManager._dispatchKeyMessage
#9      KeyEventManager.handleRawKeyMessage
#10     BasicMessageChannel.setMessageHandler.<anonymous closure>
#11     BasicMessageChannel.setMessageHandler.<anonymous closure>
#12     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
#13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
#14     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#18     _invoke2 (dart:ui/hooks.dart:189:10)
#19     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#20     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#21     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#22     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:589:22)
#23     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 5 frames from class _AssertionError and dart:async)
KeyMessage: KeyMessage([KeyDownEvent#fc994(physicalKey: PhysicalKeyboardKey#7004f(usbHidUsage: "0x0007004f", debugName: "Arrow Right"), logicalKey: LogicalKeyboardKey#00303(keyId: "0x100000303", keyLabel: "Arrow Right", debugName: "Arrow Right"), character: "UIKeyInputRightArrow", timeStamp: 64:51:42.543241)])
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
'package:calendar_date_picker2/src/widgets/calendar_date_picker2.dart': Failed assertion: line 680 pos 12: '_focusedDay != null': is not true.
════════════════════════════════════════════════════════════════════════════════

```
</details>

**Platforms (please complete the following information):**
 - Platforms: [iOS, Mac]

**Minimum Reproduceable Repo**

<details>
<summary>Code sample</summary>

```dart
import 'package:calendar_date_picker2/calendar_date_picker2.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final _selected = ValueNotifier('pick!');
  MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
            child: ValueListenableBuilder<String>(
                valueListenable: _selected,
                builder: (_, selected, __) {
                  return Text(selected);
                })),
        floatingActionButton: Builder(builder: (context) {
          return FloatingActionButton(
            child: const Icon(Icons.calendar_today),
            onPressed: () async {
              final results = await showCalendarDatePicker2Dialog(
                context: context,
                config: CalendarDatePicker2WithActionButtonsConfig(
                  calendarType: CalendarDatePicker2Type.range,
                  shouldCloseDialogAfterCancelTapped: true,
                ),
                dialogSize: const Size(325, 400),
                borderRadius: 15,
              );
              if (results != null) {
                _selected.value = results.toString();
              }
            },
          );
        }),
      ),
    );
  }
}

```
</details>

**Comment by theideasaler** [comment]
@zuvola thanks for pointing out this issue and providing the reproducible code. This issue is fixed in https://github.com/theideasaler/calendar_date_picker2/commit/b7e5bab6b34de6a14774a7dd6af205f92a853a06

**Comment by zuvola** [comment]
I have confirmed that it has been corrected.
Thank you for your quick response.
